### PR TITLE
Add type to undefined constant

### PR DESCRIPTION
**Pull request by pkoenig10**
## Before this PR
Compiling conjure-typescript generated files fails with the following error due to changes in #137.
```
error TS7005: Variable '__undefined' implicitly has an 'any' type.
```

## After this PR
Compiling conjure-typescript generated files succeeds.

Ideally we would have tests that compile the generated code. But I'm not the right person to make that change, so I'll leave it for a follow up.

### CODE REVIEW

**Comment by ferozco** [comment]
@pkoenig10 i've opened https://github.com/palantir/conjure-typescript/pull/141 which also adds ete test to prevent this from happening again
