### PR TITLE
Generate correct code for empty enums

### PR DESCRIPTION
**Pull request by p-szm**
Fixes a regression introduced in https://github.com/palantir/conjure-typescript/pull/170

## Before this PR
Empty enums like this one:
```
AircraftGeoPointField:
    values: []
```
resulted in this incorrect code:
```
export namespace AircraftGeoPointField {
}

export type AircraftGeoPointField = keyof typeof AircraftGeoPointField;
                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// error TS2708: Cannot use namespace 'AircraftGeoPointField' as a value.
// error TS4081: Exported type alias 'AircraftGeoPointField' has or is using private name 'AircraftGeoPointField'.
```

## After this PR
we generate this code:
```
export const AircraftGeoPointField = {};

export type AircraftGeoPointField = void;
```

### CODE REVIEW

**Comment by p-szm** [comment]
We probably should cherry pick this onto the `4.x` release because we just released a `5.x` version a few days ago

File: src/commands/generate/typeGenerator.ts [hunk 1]
```diff
@@ -66,32 +66,57 @@ export function generateType(
 export async function generateEnum(definition: IEnumDefinition, simpleAst: SimpleAst): Promise<void> {
     const sourceFile = simpleAst.createSourceFile(definition.typeName);
 
-    const namespaceDefinition = sourceFile.addNamespace({
-        isExported: true,
-        name: definition.typeName.name,
-        typeAliases: definition.values.map(enumValue => ({
+    if (definition.values.length > 0) {
```
Comment (ferozco) [inline src/commands/generate/typeGenerator.ts:69]: can we dedupe the code? seems like a lot of the code in the branches is very similar

File: src/commands/generate/__tests__/resources/test-cases/example-types/product/emptyEnum.ts [hunk 2]
```diff
@@ -0,0 +1,3 @@
+export const EmptyEnum = {};
```
Comment (ferozco) [inline src/commands/generate/__tests__/resources/test-cases/example-types/product/emptyEnum.ts:1]: does this still allow you to iterate the keys of the empty enum?

Comment (p-szm) [reply src/commands/generate/__tests__/resources/test-cases/example-types/product/emptyEnum.ts:1]: `namespace EmptyEnum {}` does not, but `const EmptyEnum = {}` does (because it's just a normal object)

File: src/commands/generate/typeGenerator.ts (hunk 1 above)
Comment (p-szm) [reply src/commands/generate/typeGenerator.ts:69]: Most of the code is actually pretty different. These are pretty much the only things that are duplicated:
```
        if (definition.docs != null) {
            variableStatement.addJsDoc(definition.docs);
        }
```
```
        sourceFile.addTypeAlias({
            isExported: true,
            name: definition.typeName.name,
```
I'm not sure it's worth deduping these things, but I can introduce functions that abstract some of this away.

I can also try unifying these code paths a bit more but I'm pretty sure it will make it less readable due to increased complexity.

What do you think?

**Comment by ferozco** [comment]
👍
